// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API key here generated by firebase',
    appId: '1:277042213440:web:30d0223a334772a0fde5a5',
    messagingSenderId: '277042213440',
    projectId: 'notifications-8d33c',
    authDomain: 'notifications-8d33c.firebaseapp.com',
    storageBucket: 'notifications-8d33c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API key here generated by firebase',
    appId: '1:277042213440:android:2a02aef2e82892e2fde5a5',
    messagingSenderId: '277042213440',
    projectId: 'notifications-8d33c',
    storageBucket: 'notifications-8d33c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API key here generated by firebase',
    appId: '1:277042213440:ios:e794f85ab050f73cfde5a5',
    messagingSenderId: '277042213440',
    projectId: 'notifications-8d33c',
    storageBucket: 'notifications-8d33c.appspot.com',
    iosBundleId: 'com.example.notificationsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API key here generated by firebase',
    appId: '1:277042213440:ios:e794f85ab050f73cfde5a5',
    messagingSenderId: '277042213440',
    projectId: 'notifications-8d33c',
    storageBucket: 'notifications-8d33c.appspot.com',
    iosBundleId: 'com.example.notificationsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API key here generated by firebase',
    appId: '1:277042213440:web:a712fa14c24a7ff0fde5a5',
    messagingSenderId: '277042213440',
    projectId: 'notifications-8d33c',
    authDomain: 'notifications-8d33c.firebaseapp.com',
    storageBucket: 'notifications-8d33c.appspot.com',
  );

}
